%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-rmw-gurumdds-cpp
Version:        4.2.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rmw_gurumdds_cpp package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-rolling-gurumdds-cmake-module
Requires:       ros-rolling-rcutils
Requires:       ros-rolling-rmw
Requires:       ros-rolling-rmw-dds-common
Requires:       ros-rolling-rosidl-runtime-c
Requires:       ros-rolling-rosidl-runtime-cpp
Requires:       ros-rolling-rosidl-typesupport-introspection-c
Requires:       ros-rolling-rosidl-typesupport-introspection-cpp
Requires:       ros-rolling-ros-workspace
BuildRequires:  ros-rolling-ament-cmake-ros
BuildRequires:  ros-rolling-gurumdds-cmake-module
BuildRequires:  ros-rolling-rcutils
BuildRequires:  ros-rolling-rmw
BuildRequires:  ros-rolling-rmw-dds-common
BuildRequires:  ros-rolling-rosidl-cmake
BuildRequires:  ros-rolling-rosidl-generator-dds-idl
BuildRequires:  ros-rolling-rosidl-runtime-c
BuildRequires:  ros-rolling-rosidl-runtime-cpp
BuildRequires:  ros-rolling-rosidl-typesupport-introspection-c
BuildRequires:  ros-rolling-rosidl-typesupport-introspection-cpp
BuildRequires:  ros-rolling-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-rolling-ament-lint-auto
BuildRequires:  ros-rolling-ament-lint-common
%endif

%description
Implement the ROS middleware interface using GurumNetworks GurumDDS static code
generation in C++.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/rolling" \
    -DAMENT_PREFIX_PATH="/opt/ros/rolling" \
    -DCMAKE_PREFIX_PATH="/opt/ros/rolling" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Tue Mar 07 2023 Youngjin Yun <youngjin@gurum.cc> - 4.2.0-1
- Autogenerated by Bloom

* Wed Nov 30 2022 Youngjin Yun <youngjin@gurum.cc> - 4.1.2-1
- Autogenerated by Bloom

* Mon Nov 07 2022 Youngjin Yun <youngjin@gurum.cc> - 4.1.1-1
- Autogenerated by Bloom

* Mon May 09 2022 Youngjin Yun <youngjin@gurum.cc> - 4.0.0-1
- Autogenerated by Bloom

* Fri Jan 14 2022 Youngjin Yun <youngjin@gurum.cc> - 3.1.2-2
- Autogenerated by Bloom

* Wed Jan 05 2022 Youngjin Yun <youngjin@gurum.cc> - 3.1.2-1
- Autogenerated by Bloom

* Thu Oct 14 2021 Youngjin Yun <youngjin@gurum.cc> - 3.0.9-1
- Autogenerated by Bloom

* Thu Oct 14 2021 Youngjin Yun <youngjin@gurum.cc> - 3.0.8-1
- Autogenerated by Bloom

* Mon Sep 27 2021 Youngjin Yun <youngjin@gurum.cc> - 3.0.7-1
- Autogenerated by Bloom

* Thu Sep 23 2021 Youngjin Yun <youngjin@gurum.cc> - 3.0.6-1
- Autogenerated by Bloom

* Thu Sep 23 2021 Youngjin Yun <youngjin@gurum.cc> - 3.0.5-1
- Autogenerated by Bloom

* Thu Sep 02 2021 Youngjin Yun <youngjin@gurum.cc> - 3.0.4-1
- Autogenerated by Bloom

* Thu Aug 19 2021 Youngjin Yun <youngjin@gurum.cc> - 3.0.3-1
- Autogenerated by Bloom

* Wed Jul 14 2021 Youngjin Yun <youngjin@gurum.cc> - 3.0.2-1
- Autogenerated by Bloom

* Wed Jul 07 2021 Youngjin Yun <youngjin@gurum.cc> - 3.0.1-1
- Autogenerated by Bloom

* Thu Apr 29 2021 Youngjin Yun <youngjin@gurum.cc> - 3.0.0-1
- Autogenerated by Bloom

* Thu Apr 22 2021 Youngjin Yun <youngjin@gurum.cc> - 2.1.4-1
- Autogenerated by Bloom

* Mon Apr 12 2021 Youngjin Yun <youngjin@gurum.cc> - 2.1.3-1
- Autogenerated by Bloom

* Mon Mar 22 2021 Youngjin Yun <youngjin@gurum.cc> - 2.1.2-1
- Autogenerated by Bloom

* Fri Mar 12 2021 Youngjin Yun <youngjin@gurum.cc> - 2.1.1-1
- Autogenerated by Bloom

